# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('large_img', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('upc', models.TextField(blank=True, null=True)),
                ('sku', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('crawled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
